### ISSUE TITLE
Image-mode buffers change non-ASCII symbols in mode-line

### ISSUE THREAD

**Issue by ghost** [josegpt/display-wttr#19]
After activating `display-wttr-mode`, when I navigate to `image-mode` or `pdf-view` buffers (which use Image-mode under the hood), some icons like the Sun symbol will be changed to another font.

![20220822-224654](https://user-images.githubusercontent.com/96617722/186015914-6f44b5ab-86d2-417b-8896-b30b97b551a0.jpg)
![20220822-224727](https://user-images.githubusercontent.com/96617722/186016093-b8ea55be-d187-484d-8f7d-d7f7b3bef989.jpg)

I've raised this issue on #emacs but was unable to get any help. I'd like to know if you can reproduce this. I have Noto Color Emoji installed as the fontset font and Iosevka as the default font in Emacs.

The following are the steps to reproduce the issue:

1. Start a fresh Emacs with `emacs -Q`. 
2. Install `display-wttr` from Melpa as per the project README.
3. Configure `display-wttr` with the following.

```emacs-lisp
(display-wttr-mode)
 (with-eval-after-load 'display-wttr
   (custom-set-variables
     '(display-wttr-format "%c %t")))
```

4. Install and set the fontset default font.

```emacs-lisp
(set-fontset-font t 'symbol "Noto Color Emoji" nil 'append)
(set-fontset-font "fontset-default" nil (font-spec :name "Noto Color Emoji"))
(set-fontset-font t 'unicode "Noto Color Emoji" nil 'append)
(setq use-default-font-for-symbols nil)
```

5. Navigate to a file image (in my case, a `.png`) 
6. Encounter the error shown by the screenshots.

**Comment by josegpt** [comment]
I tried to reproduce what you mentioned and I was not able to get the same result. What version of `Emacs` are you running?

I am using Emacs `29.0.50-1.0a5477b`

**Comment by ghost** [comment]
I've just tried again on the version of Emacs I'm on, `GNU Emacs 28.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.30, cairo version 1.16.0)`, and it still occurs. Maybe it was fixed on 29? Anyway, I'll see if I can test it on 29 without breaking my configuration given as EXWM does not currently play well with this version as per [this issue](https://github.com/ch11ng/exwm/issues/873). Is there a chance you could test it on 28 too?

**Comment by josegpt** [comment]
It seems to be fixed on Emacs 29, because I just checked Emacs 28.1 and it only happened with the `☀️` emoji while on `image-mode`. I would like to let you know that I have been using Emacs 29 with EXWM and I have no issues.

**Comment by ghost** [comment]
Ah good to know it was fixed! I'll close the issue then. Thank you for the heads up on EXWM and Emacs 29, I'll give it another shot.
